### ISSUE TITLE
What kind of error is this?

### ISSUE THREAD

**Issue by MicheleMassa802** [karansher/computer-graphics-bounding-volume-hierarchy#33]
![image](https://user-images.githubusercontent.com/75578291/198754660-7cbf4364-dce2-4d34-9395-a6b7838c8006.png)
Like I have never seen something like this, the vector inputs have that weird matrix form, nothing is being highlighted as the normal errors that you see when you have a syntax error. I am just confused at what this is. Keep in mind this is for the modified implementation of ray intersect triangle, which makes this even worse, I made sure to transpose my vectors, and the algorithm is the same, why am I getting this weird error?

**Comment by eon704** [comment]
Looks like compiler can't find `.transpose()` method.

Have you by chance included the `Eigen/Dense`?

**Comment by MicheleMassa802** [comment]
Even after doing so I still getting a similar type of error, but a different one at least, thank you, I'll look into this new error. Now that I have included Eigen/Dense its still complaining about 'scalar difference' and a bunch of other stuff that didnt happen previously, still feels so weird

**Comment by MicheleMassa802** [comment]
It feels like an error in imports, I have also included Eigen/Geometry as I realized I had it in my asn3 code but I'm still getting the same.

**Comment by MicheleMassa802** [comment]
Just solved it, man python wouldnt do this to me I hate c++ lol. Thank you so much for your quick answer. Sent me a lifeline :)
